### ISSUE TITLE
Split code into directories

### ISSUE THREAD

**Issue by CSSolomon** [Gamerguy123lo/EXPONOS#2]
Your code is currently all placed in a flat hierarchy, i.e. without any logical grouping of files. If you check out the repositories of well-established open-source projects, e.g. [numy](https://github.com/numpy/numpy) you will see that there is a hierarchy in how files are placed. Usually it goes a bit like this:

1. Root folder (base folder, not in a directory)
    1. `README.md` (Intro to the file
    2. `LICENSE` (The license you're distributing the software under)
    3. `INSTALL` (install instructions) 
    4. gitlab related files (`.gitignore`, `.gitattributes`, `.gitlab-ci.yml` or similar
    5. Setup files (E.g. for visualstudio)
1. `/src` The source code (e.g. your `EXPONOS.cpp` files)
2. `/media` Here you should place your `.wav`, `.mp3` files and so on
3. `/test` Here you can add all files related to test. Test scripts, test automation and so on

**Comment by Gamerguy123lo** [comment]
If the files are splitted in to different subfolders they won't be recognised by Visual Studio thus not working.

**Comment by CSSolomon** [comment]
You need to change the directories your code is searching the files in. E.g.:
```c++
                     PlaySound(TEXT("ding.wav"), GetModuleHandle(NULL), SND_FILENAME | SND_ASYNC);
```
would need to become
```c++
                     PlaySound(TEXT("..\Media\ding.wav"), GetModuleHandle(NULL), SND_FILENAME | SND_ASYNC);
```
as the location has changed.

I would also propose changing the name from `Media` to `media`, i.e. all lower-case letters, in which case the change would be
```c++
                     PlaySound(TEXT("..\media\ding.wav"), GetModuleHandle(NULL), SND_FILENAME | SND_ASYNC);
```
even if Windows doesn't really care for case.

To better understand what the issue is, have a look at [relative vs absolute paths](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)
